### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by Lizdev-05** [PinkMoon25/Book_an_appointment_API#13]
There are 4 members in our team. @Lizdev-05  has been assigned to Team Member 1 task, @ademibowale to Team Member 2. @kelomo2502 to Team Member 3, and @PinkMoon25  to Team Member 4. Here is the [link](https://github.com/users/PinkMoon25/projects/6) to the project.
Attached below 👇 is the capture of the state of our kanban 
<img width="1470" alt="Screenshot 2022-11-23 at 18 27 25" src="https://user-images.githubusercontent.com/73854999/203611681-1ed723e1-1f1f-44ba-b766-c2ebd5387b33.png">

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Lizdev-05** [comment]
Thank you for reviewing our code

**Comment by mcrd25** [comment]
Hi Team, 

Great work so far👏 
However, there are some issues preventing me from giving the 👍 


- Team Member 2 has only 10 points associated which is a 5 or greater difference than the next closest member, Team Member 1, who has 16.5pts assigned (The other two members have 18 each as well). Team Member, 2  needs more tasks assigned so that the share is equitable. i.e. difference < 5 or difference should not be >= 5 among the members of the team.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Lizdev-05** [comment]
Good day @mcrd25 , According to the requirements, we have made the required changes and presently no team member has a difference of more than 5 points.  😊
<img width="1470" alt="Screenshot 2022-11-24 at 10 01 12" src="https://user-images.githubusercontent.com/73854999/203739540-f1d4c9e5-13ba-42f0-bc1b-4e5cee4998ac.png">

**Comment by Meltrust** [comment]
Hi @mcrd25,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointing of the tasks is fair now✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lizdev-05** [comment]
Thank you for reviewing and approving our work
